CREATE TABLE IF NOT EXISTS  User(
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    address2 VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
    );